name: nbp_currency_checker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  auto_route: ^9.3.0+1
  bloc: ^9.0.0
  fimber: ^0.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  injectable: ^2.5.0
  very_good_analysis: ^7.0.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
