name: nbp_currency_checker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  auto_route: ^9.3.0+1
  bloc: ^9.0.0
  chopper: ^8.0.3
  decimal: ^3.0.2
  fimber: ^0.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  injectable: ^2.5.0
  intl: any
  json_annotation: ^4.9.0
  money2: ^5.4.6
  retrofit: ^4.4.2
  very_good_analysis: ^7.0.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  bloc_test: ^10.0.0
  build_runner: ^2.4.14
  chopper_generator: ^8.0.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  retrofit_generator: ^9.1.7

flutter:
  uses-material-design: true
  generate: true
